name:                accelerate-tabular
version:             0.1.0.0
github:              "Tjalle-S/accelerate-tabular"
license:             BSD-3-Clause
author:              "Tjalle Schoonderwoerd"
# maintainer:          "example@example.com"
copyright:           "2025 Tjalle Schoonderwoerd"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Tjalle-S/accelerate-tabular#readme>

dependencies:
- base >= 4.16 && < 5
- accelerate
- accelerate-llvm
- accelerate-llvm-native
- containers-accelerate
- hashable-accelerate
- deepseq
- microlens >= 0.5.0.0 && < 0.6
- template-haskell >=2.19 && < 2.20

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  accelerate-tabular-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-n2M
    - -with-rtsopts=-A64M
    dependencies:
    - accelerate-tabular

  accelerate-tabular-examples:
    main:                Main.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerate-tabular
    - criterion
    - criterion-measurement
    - deepseq
    - random

tests:
  accelerate-tabular-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerate-tabular
    - hedgehog
    - tasty
    - tasty-hedgehog

benchmarks:
  accelerate-tabular-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerate-tabular
    - criterion
    - random
